language: bash

sudo: required

services:
  - docker

script:
- docker create -v /opt/android-sdk-linux --name my-android-volume jacekmarchwicki/android:java8-r24-4-1 /bin/true
- docker run -it -v /home/travis/build/matzew/helloworld-android-gradle/:/app:z --volumes-from my-android-volume -e AG_MOBILE_SDK=/opt/android-sdk-linux -e ANDROID_HOME=/opt/android-sdk-linux -e PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/mobile-sdk/tools:/opt/android-sdk-linux/tools aerogear/mobile-sdk build
